---
- name: 'Initial install and configuration'
  become: true
  hosts: postgres
  vars:
    postgres_users_no_log: false # включаем отображение паролей в консоле для отладки, само собой в продакшене это надо выключить
    postgresql_users:
      - name: postgres
        password: password
  roles:
    - ultimate-app
    - geerlingguy.nginx
    - postgres-minimal
  tasks:
  - name: "Update nginx.conf"
    ansible.builtin.template:
      src: nginx.j2
      dest: /etc/nginx/nginx.conf
      owner: nginx
      group: nginx
      mode: u=rw,g=r,o=r
  - name: "Reload nginx"
    ansible.builtin.systemd:
      state: reloaded
      name: nginx